version: '3.9'

services:
  user-service:
    container_name: user-service
    image: vendee-cinema/user-service:dev
    build:
      context: .
      dockerfile: .dockerfile
    restart: always
    env_file:
      - .env.production.local
    networks:
      - vendee-cinema

networks:
  vendee-cinema:
    external: true
